// Copyright (c) 2022-2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Iam.Model;

namespace AccelByte.Sdk.Api.Iam.Operation
{
    /// <summary>
    /// DeleteUserInformation
    ///
    /// ## The endpoint is going to be deprecated
    /// ### Endpoint migration guide
    /// - **Substitute endpoint: _/iam/v3/admin/namespaces/{namespace}/users/{userId}/information [DELETE]_**
    /// </summary>
    [Obsolete(DiagnosticId ="ab_deprecated_operation")]
    public class DeleteUserInformation : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static DeleteUserInformationBuilder Builder { get => new DeleteUserInformationBuilder(); }

        public interface IDeleteUserInformationBuilder
        {





        }

        public abstract class DeleteUserInformationAbstractBuilder<TImpl>
            : OperationBuilder<TImpl>, IDeleteUserInformationBuilder
            where TImpl : DeleteUserInformationAbstractBuilder<TImpl>
        {





            public DeleteUserInformationAbstractBuilder() { }

            public DeleteUserInformationAbstractBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public DeleteUserInformation Build(
                string namespace_,
                string userId
            )
            {
                DeleteUserInformation op = new DeleteUserInformation(this,
                    namespace_,                    
                    userId                    
                );

                op.SetBaseFields<TImpl>(this);
                return op;
            }

            [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
            protected DeleteUserInformation.Response InternalExecute(
                string namespace_,
                string userId
            )
            {
                DeleteUserInformation op = Build(
                    namespace_,
                    userId
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<DeleteUserInformation.Response> InternalExecuteAsync(
                string namespace_,
                string userId
            )
            {
                DeleteUserInformation op = Build(
                    namespace_,
                    userId
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        public class DeleteUserInformationBuilder : DeleteUserInformationAbstractBuilder<DeleteUserInformationBuilder>
        {
            public DeleteUserInformationBuilder() : base() { }

            public DeleteUserInformationBuilder(IAccelByteSdk sdk) : base(sdk) { }

            [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
            public DeleteUserInformation.Response Execute(
                string namespace_,
                string userId
            )
            {
                return InternalExecute(
                    namespace_,
                    userId
                );
            }
            public async Task<DeleteUserInformation.Response> ExecuteAsync(
                string namespace_,
                string userId
            )
            {
                return await InternalExecuteAsync(
                    namespace_,
                    userId
                );
            }
        }


        public DeleteUserInformation(IDeleteUserInformationBuilder builder,
            string namespace_,
            string userId
        )
        {
            PathParams["namespace"] = namespace_;
            PathParams["userId"] = userId;
            
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse
        {

            public RestErrorResponse? Error401 { get; set; } = null;

            public RestErrorResponse? Error403 { get; set; } = null;

            public string Error404 { get; set; } = "";


            protected override string GetFullOperationId() => "Iam::Users::DeleteUserInformation";
        }

        #endregion

        public DeleteUserInformation(
            string namespace_,            
            string userId            
        )
        {
            PathParams["namespace"] = namespace_;
            PathParams["userId"] = userId;
            
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/iam/namespaces/{namespace}/users/{userId}/information";

        public override HttpMethod Method => HttpMethod.Delete;

        public override List<string> Consumes => new() { "application/json" };

        public override List<string> Produces => new() { "application/json" };
        
        public DeleteUserInformation.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new DeleteUserInformation.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            int statusCode = (int)code;
            if (statusCode >= 200 && statusCode < 300)
            {
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)401)
            {
                response.Payload = payload.ReadToString();
                response.Error401 = JsonSerializer.Deserialize<RestErrorResponse>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error401!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)403)
            {
                response.Payload = payload.ReadToString();
                response.Error403 = JsonSerializer.Deserialize<RestErrorResponse>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error403!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)404)
            {
                response.Payload = payload.ReadToString();
                response.Error404 = response.Payload;
                response.Error = new ApiError("-1", response.Error404!);
            }

            return response;
        }
    }

}