// Copyright (c) 2022-2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Match2.Model;

namespace AccelByte.Sdk.Api.Match2.Operation
{
    /// <summary>
    /// adminUpdateXRayConfig
    ///
    /// Admin update XRay config
    /// </summary>
    public class AdminUpdateXRayConfig : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AdminUpdateXRayConfigBuilder Builder { get => new AdminUpdateXRayConfigBuilder(); }

        public interface IAdminUpdateXRayConfigBuilder
        {





        }

        public abstract class AdminUpdateXRayConfigAbstractBuilder<TImpl>
            : OperationBuilder<TImpl>, IAdminUpdateXRayConfigBuilder
            where TImpl : AdminUpdateXRayConfigAbstractBuilder<TImpl>
        {





            public AdminUpdateXRayConfigAbstractBuilder() { }

            public AdminUpdateXRayConfigAbstractBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public AdminUpdateXRayConfig Build(
                ModelsXRayConfigHttpUpdateRequest body,
                string namespace_
            )
            {
                AdminUpdateXRayConfig op = new AdminUpdateXRayConfig(this,
                    body,                    
                    namespace_                    
                );

                op.SetBaseFields<TImpl>(this);
                return op;
            }

            protected AdminUpdateXRayConfig.Response InternalExecute(
                ModelsXRayConfigHttpUpdateRequest body,
                string namespace_
            )
            {
                AdminUpdateXRayConfig op = Build(
                    body,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<AdminUpdateXRayConfig.Response> InternalExecuteAsync(
                ModelsXRayConfigHttpUpdateRequest body,
                string namespace_
            )
            {
                AdminUpdateXRayConfig op = Build(
                    body,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        public class AdminUpdateXRayConfigBuilder : AdminUpdateXRayConfigAbstractBuilder<AdminUpdateXRayConfigBuilder>
        {
            public AdminUpdateXRayConfigBuilder() : base() { }

            public AdminUpdateXRayConfigBuilder(IAccelByteSdk sdk) : base(sdk) { }

            public AdminUpdateXRayConfig.Response Execute(
                ModelsXRayConfigHttpUpdateRequest body,
                string namespace_
            )
            {
                return InternalExecute(
                    body,
                    namespace_
                );
            }
            public async Task<AdminUpdateXRayConfig.Response> ExecuteAsync(
                ModelsXRayConfigHttpUpdateRequest body,
                string namespace_
            )
            {
                return await InternalExecuteAsync(
                    body,
                    namespace_
                );
            }
        }


        public AdminUpdateXRayConfig(IAdminUpdateXRayConfigBuilder builder,
            ModelsXRayConfigHttpUpdateRequest body,
            string namespace_
        )
        {
            PathParams["namespace"] = namespace_;
            
            

            
            
            BodyParams = body;
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse
        {

            public ResponseError? Error400 { get; set; } = null;

            public ResponseError? Error401 { get; set; } = null;

            public ResponseError? Error403 { get; set; } = null;

            public ResponseError? Error500 { get; set; } = null;


            protected override string GetFullOperationId() => "Match2::XRayConfig::AdminUpdateXRayConfig";
        }

        #endregion

        public AdminUpdateXRayConfig(
            string namespace_,            
            Model.ModelsXRayConfigHttpUpdateRequest body            
        )
        {
            PathParams["namespace"] = namespace_;
            
            

            
            
            BodyParams = body;
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/match2/v1/admin/namespaces/{namespace}/xray/config";

        public override HttpMethod Method => HttpMethod.Post;

        public override List<string> Consumes => new() { "application/json" };

        public override List<string> Produces => new() { "application/json" };
        
        public AdminUpdateXRayConfig.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new AdminUpdateXRayConfig.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            int statusCode = (int)code;
            if (statusCode >= 200 && statusCode < 300)
            {
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)400)
            {
                response.Payload = payload.ReadToString();
                response.Error400 = JsonSerializer.Deserialize<ResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error400!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)401)
            {
                response.Payload = payload.ReadToString();
                response.Error401 = JsonSerializer.Deserialize<ResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error401!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)403)
            {
                response.Payload = payload.ReadToString();
                response.Error403 = JsonSerializer.Deserialize<ResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error403!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)500)
            {
                response.Payload = payload.ReadToString();
                response.Error500 = JsonSerializer.Deserialize<ResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error500!.TranslateToApiError();
            }

            return response;
        }
    }

}