// Copyright (c) 2022-2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Iam.Model;

namespace AccelByte.Sdk.Api.Iam.Operation
{
    /// <summary>
    /// PublicEnableMyEmailV4
    ///
    /// This endpoint is used to enable 2FA email.
    /// </summary>
    public class PublicEnableMyEmailV4 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static PublicEnableMyEmailV4Builder Builder { get => new PublicEnableMyEmailV4Builder(); }

        public class PublicEnableMyEmailV4Builder
            : OperationBuilder<PublicEnableMyEmailV4Builder>
        {





            internal PublicEnableMyEmailV4Builder() { }

            internal PublicEnableMyEmailV4Builder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public PublicEnableMyEmailV4 Build(
                string code,
                string namespace_
            )
            {
                PublicEnableMyEmailV4 op = new PublicEnableMyEmailV4(this,
                    code,
                    namespace_
                );

                op.SetBaseFields<PublicEnableMyEmailV4Builder>(this);
                return op;
            }

            public void Execute(
                string code,
                string namespace_
            )
            {
                PublicEnableMyEmailV4 op = Build(
                    code,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                op.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
            }
        }

        private PublicEnableMyEmailV4(PublicEnableMyEmailV4Builder builder,
            string code,
            string namespace_
        )
        {
            PathParams["namespace"] = namespace_;


            if (code is not null) FormParams["code"] = code;





            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public PublicEnableMyEmailV4(
            string namespace_,
            string code
        )
        {
            PathParams["namespace"] = namespace_;


            if (code is not null) FormParams["code"] = code;





            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/iam/v4/public/namespaces/{namespace}/users/me/mfa/email/enable";

        public override HttpMethod Method => HttpMethod.Post;

        public override List<string> Consumes => new() { "application/x-www-form-urlencoded" };

        public override List<string> Produces => new() { "application/json" };

        public void ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return;
            }

            var payloadString = payload.ReadToString();

            throw new HttpResponseException(code, payloadString);
        }
    }

}