// Copyright (c) 2022-2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Platform.Model;

namespace AccelByte.Sdk.Api.Platform.Operation
{
    /// <summary>
    /// acquireItem
    ///
    ///  [SERVICE COMMUNICATION ONLY] This api is used for acquiring a published item while the item is maxCount limited, it will decrease the sale available count.
    /// Other detail info:
    /// 
    ///   * Returns : acquire result
    /// </summary>
    public class AcquireItem : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AcquireItemBuilder Builder { get => new AcquireItemBuilder(); }

        public class AcquireItemBuilder
            : OperationBuilder<AcquireItemBuilder>
        {


            public Model.ItemAcquireRequest? Body { get; set; }




            internal AcquireItemBuilder() { }

            internal AcquireItemBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }



            public AcquireItemBuilder SetBody(Model.ItemAcquireRequest _body)
            {
                Body = _body;
                return this;
            }




            public AcquireItem Build(
                string itemId,
                string namespace_
            )
            {
                AcquireItem op = new AcquireItem(this,
                    itemId,
                    namespace_
                );

                op.SetBaseFields<AcquireItemBuilder>(this);
                return op;
            }

            public Model.ItemAcquireResult? Execute(
                string itemId,
                string namespace_
            )
            {
                AcquireItem op = Build(
                    itemId,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
            }
            public async Task<Model.ItemAcquireResult?> ExecuteAsync(
                string itemId,
                string namespace_
            )
            {
                AcquireItem op = Build(
                    itemId,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
            }
        }

        private AcquireItem(AcquireItemBuilder builder,
            string itemId,
            string namespace_
        )
        {
            PathParams["itemId"] = itemId;
            PathParams["namespace"] = namespace_;





            BodyParams = builder.Body;


            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public AcquireItem(
            string itemId,
            string namespace_,
            Model.ItemAcquireRequest body
        )
        {
            PathParams["itemId"] = itemId;
            PathParams["namespace"] = namespace_;





            BodyParams = body;


            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/platform/admin/namespaces/{namespace}/items/{itemId}/acquire";

        public override HttpMethod Method => HttpMethod.Put;

        public override List<string> Consumes => new() { "application/json" };

        public override List<string> Produces => new() { "application/json" };

        public Model.ItemAcquireResult? ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return null;
            }
            else if (code == (HttpStatusCode)201)
            {
                return JsonSerializer.Deserialize<Model.ItemAcquireResult>(payload, ResponseJsonOptions);
            }
            else if (code == (HttpStatusCode)200)
            {
                return JsonSerializer.Deserialize<Model.ItemAcquireResult>(payload, ResponseJsonOptions);
            }

            var payloadString = payload.ReadToString();

            throw new HttpResponseException(code, payloadString);
        }
    }

}