// Copyright (c) 2022-2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Platform.Model;

namespace AccelByte.Sdk.Api.Platform.Operation
{
    /// <summary>
    /// listItemTypeConfigs
    ///
    ///  [Not Supported Yet In Starter] This API is used to get all item type configs.
    /// 
    /// Other detail info:
    /// 
    ///   * Required permission : resource="ADMIN:ITEM:CONFIG", action=2 (READ)
    ///   *  Returns : the list of items
    /// </summary>
    public class ListItemTypeConfigs : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static ListItemTypeConfigsBuilder Builder { get => new ListItemTypeConfigsBuilder(); }

        public class ListItemTypeConfigsBuilder
            : OperationBuilder<ListItemTypeConfigsBuilder>
        {





            internal ListItemTypeConfigsBuilder() { }

            internal ListItemTypeConfigsBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public ListItemTypeConfigs Build(
            )
            {
                ListItemTypeConfigs op = new ListItemTypeConfigs(this
                );

                op.SetBaseFields<ListItemTypeConfigsBuilder>(this);
                return op;
            }

            public List<Model.ItemTypeConfigInfo>? Execute(
            )
            {
                ListItemTypeConfigs op = Build(
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
            }
            public async Task<List<Model.ItemTypeConfigInfo>?> ExecuteAsync(
            )
            {
                ListItemTypeConfigs op = Build(
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
            }
        }

        private ListItemTypeConfigs(ListItemTypeConfigsBuilder builder
        )
        {







            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public ListItemTypeConfigs(
        )
        {







            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/platform/admin/items/configs";

        public override HttpMethod Method => HttpMethod.Get;

        public override List<string> Consumes => new() { };

        public override List<string> Produces => new() { "application/json" };

        public List<Model.ItemTypeConfigInfo>? ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return null;
            }
            else if (code == (HttpStatusCode)201)
            {
                return JsonSerializer.Deserialize<List<Model.ItemTypeConfigInfo>>(payload, ResponseJsonOptions);
            }
            else if (code == (HttpStatusCode)200)
            {
                return JsonSerializer.Deserialize<List<Model.ItemTypeConfigInfo>>(payload, ResponseJsonOptions);
            }

            var payloadString = payload.ReadToString();

            throw new HttpResponseException(code, payloadString);
        }
    }

}