// Copyright (c) 2022-2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Cloudsave.Model;

namespace AccelByte.Sdk.Api.Cloudsave.Operation
{
    /// <summary>
    /// adminGetGameRecordHandlerV1
    ///
    /// Get a record by its key in namespace-level.
    /// </summary>
    public class AdminGetGameRecordHandlerV1 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AdminGetGameRecordHandlerV1Builder Builder { get => new AdminGetGameRecordHandlerV1Builder(); }

        public interface IAdminGetGameRecordHandlerV1Builder
        {





        }

        public abstract class AdminGetGameRecordHandlerV1AbstractBuilder<TImpl>
            : OperationBuilder<TImpl>, IAdminGetGameRecordHandlerV1Builder
            where TImpl : AdminGetGameRecordHandlerV1AbstractBuilder<TImpl>
        {





            public AdminGetGameRecordHandlerV1AbstractBuilder() { }

            public AdminGetGameRecordHandlerV1AbstractBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public AdminGetGameRecordHandlerV1 Build(
                string key,
                string namespace_
            )
            {
                AdminGetGameRecordHandlerV1 op = new AdminGetGameRecordHandlerV1(this,
                    key,                    
                    namespace_                    
                );

                op.SetBaseFields<TImpl>(this);
                return op;
            }

            protected AdminGetGameRecordHandlerV1.Response InternalExecute(
                string key,
                string namespace_
            )
            {
                AdminGetGameRecordHandlerV1 op = Build(
                    key,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<AdminGetGameRecordHandlerV1.Response> InternalExecuteAsync(
                string key,
                string namespace_
            )
            {
                AdminGetGameRecordHandlerV1 op = Build(
                    key,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }

            protected AdminGetGameRecordHandlerV1.Response<T1> InternalExecute<T1>(
                string key,
                string namespace_
            )
            {
                AdminGetGameRecordHandlerV1 op = Build(
                    key,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse<T1>(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<AdminGetGameRecordHandlerV1.Response<T1>> InternalExecuteAsync<T1>(
                string key,
                string namespace_
            )
            {
                AdminGetGameRecordHandlerV1 op = Build(
                    key,
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse<T1>(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        public class AdminGetGameRecordHandlerV1Builder : AdminGetGameRecordHandlerV1AbstractBuilder<AdminGetGameRecordHandlerV1Builder>
        {
            public AdminGetGameRecordHandlerV1Builder() : base() { }

            public AdminGetGameRecordHandlerV1Builder(IAccelByteSdk sdk) : base(sdk) { }

            public AdminGetGameRecordHandlerV1.Response Execute(
                string key,
                string namespace_
            )
            {
                return InternalExecute(
                    key,
                    namespace_
                );
            }
            public async Task<AdminGetGameRecordHandlerV1.Response> ExecuteAsync(
                string key,
                string namespace_
            )
            {
                return await InternalExecuteAsync(
                    key,
                    namespace_
                );
            }

            public AdminGetGameRecordHandlerV1.Response<T1> Execute<T1>(
                string key,
                string namespace_
            )
            {
                return InternalExecute<T1>(
                    key,
                    namespace_
                );
            }
            public async Task<AdminGetGameRecordHandlerV1.Response<T1>> ExecuteAsync<T1>(
                string key,
                string namespace_
            )
            {
                return await InternalExecuteAsync<T1>(
                    key,
                    namespace_
                );
            }
        }


        public AdminGetGameRecordHandlerV1(IAdminGetGameRecordHandlerV1Builder builder,
            string key,
            string namespace_
        )
        {
            PathParams["key"] = key;
            PathParams["namespace"] = namespace_;
            
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse<Model.ModelsGameRecordAdminResponse>
        {

            public ModelsResponseError? Error401 { get; set; } = null;

            public ModelsResponseError? Error403 { get; set; } = null;

            public ModelsResponseError? Error404 { get; set; } = null;

            public ModelsResponseError? Error500 { get; set; } = null;


            protected override string GetFullOperationId() => "Cloudsave::AdminGameRecord::AdminGetGameRecordHandlerV1";
        }

        public class Response<T1> : ApiResponse<Model.ModelsGameRecordAdminResponse<T1>>
        {
            public ModelsResponseError? Error401 { get; set; } = null;

            public ModelsResponseError? Error403 { get; set; } = null;

            public ModelsResponseError? Error404 { get; set; } = null;

            public ModelsResponseError? Error500 { get; set; } = null;


            protected override string GetFullOperationId() => "Cloudsave::AdminGameRecord::AdminGetGameRecordHandlerV1";
        }
        #endregion

        public AdminGetGameRecordHandlerV1(
            string key,            
            string namespace_            
        )
        {
            PathParams["key"] = key;
            PathParams["namespace"] = namespace_;
            
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/cloudsave/v1/admin/namespaces/{namespace}/records/{key}";

        public override HttpMethod Method => HttpMethod.Get;

        public override List<string> Consumes => new() { "application/json" };

        public override List<string> Produces => new() { "application/json" };
        
        public AdminGetGameRecordHandlerV1.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new AdminGetGameRecordHandlerV1.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Payload = payload.ReadToString();
                response.Data = JsonSerializer.Deserialize<Model.ModelsGameRecordAdminResponse>(response.Payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)401)
            {
                response.Payload = payload.ReadToString();
                response.Error401 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error401!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)403)
            {
                response.Payload = payload.ReadToString();
                response.Error403 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error403!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)404)
            {
                response.Payload = payload.ReadToString();
                response.Error404 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error404!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)500)
            {
                response.Payload = payload.ReadToString();
                response.Error500 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error500!.TranslateToApiError();
            }

            return response;
        }

        public AdminGetGameRecordHandlerV1.Response<T1> ParseResponse<T1>(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new AdminGetGameRecordHandlerV1.Response<T1>()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }            
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Payload = payload.ReadToString();
                response.Data = JsonSerializer.Deserialize<Model.ModelsGameRecordAdminResponse<T1>>(response.Payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)401)
            {
                response.Payload = payload.ReadToString();
                response.Error401 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error401!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)403)
            {
                response.Payload = payload.ReadToString();
                response.Error403 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error403!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)404)
            {
                response.Payload = payload.ReadToString();
                response.Error404 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error404!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)500)
            {
                response.Payload = payload.ReadToString();
                response.Error500 = JsonSerializer.Deserialize<ModelsResponseError>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error500!.TranslateToApiError();
            }
            
            return response;
        }
    }

}