// Copyright (c) 2022-2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Platform.Model;

namespace AccelByte.Sdk.Api.Platform.Operation
{
    /// <summary>
    /// getOrderStatistics
    ///
    /// Get Order Statistics.
    /// Other detail info:
    /// 
    ///   * Returns : order statistics
    /// </summary>
    public class GetOrderStatistics : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static GetOrderStatisticsBuilder Builder { get => new GetOrderStatisticsBuilder(); }

        public interface IGetOrderStatisticsBuilder
        {





        }

        public abstract class GetOrderStatisticsAbstractBuilder<TImpl>
            : OperationBuilder<TImpl>, IGetOrderStatisticsBuilder
            where TImpl : GetOrderStatisticsAbstractBuilder<TImpl>
        {





            public GetOrderStatisticsAbstractBuilder() { }

            public GetOrderStatisticsAbstractBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public GetOrderStatistics Build(
                string namespace_
            )
            {
                GetOrderStatistics op = new GetOrderStatistics(this,
                    namespace_                    
                );

                op.SetBaseFields<TImpl>(this);
                return op;
            }

            protected GetOrderStatistics.Response InternalExecute(
                string namespace_
            )
            {
                GetOrderStatistics op = Build(
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<GetOrderStatistics.Response> InternalExecuteAsync(
                string namespace_
            )
            {
                GetOrderStatistics op = Build(
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        public class GetOrderStatisticsBuilder : GetOrderStatisticsAbstractBuilder<GetOrderStatisticsBuilder>
        {
            public GetOrderStatisticsBuilder() : base() { }

            public GetOrderStatisticsBuilder(IAccelByteSdk sdk) : base(sdk) { }

            public GetOrderStatistics.Response Execute(
                string namespace_
            )
            {
                return InternalExecute(
                    namespace_
                );
            }
            public async Task<GetOrderStatistics.Response> ExecuteAsync(
                string namespace_
            )
            {
                return await InternalExecuteAsync(
                    namespace_
                );
            }
        }


        public GetOrderStatistics(IGetOrderStatisticsBuilder builder,
            string namespace_
        )
        {
            PathParams["namespace"] = namespace_;
            
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse<Model.OrderStatistics>
        {


            protected override string GetFullOperationId() => "Platform::Order::GetOrderStatistics";
        }

        #endregion

        public GetOrderStatistics(
            string namespace_            
        )
        {
            PathParams["namespace"] = namespace_;
            
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/platform/admin/namespaces/{namespace}/orders/stats";

        public override HttpMethod Method => HttpMethod.Get;

        public override List<string> Consumes => new() {  };

        public override List<string> Produces => new() { "application/json" };
        
        public GetOrderStatistics.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new GetOrderStatistics.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Payload = payload.ReadToString();
                response.Data = JsonSerializer.Deserialize<Model.OrderStatistics>(response.Payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }

            return response;
        }
    }

}