// Copyright (c) 2022-2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Reporting.Model;

namespace AccelByte.Sdk.Api.Reporting.Operation
{
    /// <summary>
    /// adminCreateExtensionCategory
    ///
    /// Create extension category data
    /// </summary>
    public class AdminCreateExtensionCategory : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AdminCreateExtensionCategoryBuilder Builder { get => new AdminCreateExtensionCategoryBuilder(); }

        public class AdminCreateExtensionCategoryBuilder
            : OperationBuilder<AdminCreateExtensionCategoryBuilder>
        {





            internal AdminCreateExtensionCategoryBuilder() { }

            internal AdminCreateExtensionCategoryBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public AdminCreateExtensionCategory Build(
                RestapiExtensionCategoryApiRequest body
            )
            {
                AdminCreateExtensionCategory op = new AdminCreateExtensionCategory(this,
                    body                    
                );

                op.SetBaseFields<AdminCreateExtensionCategoryBuilder>(this);
                return op;
            }

            public AdminCreateExtensionCategory.Response Execute(
                RestapiExtensionCategoryApiRequest body
            )
            {
                AdminCreateExtensionCategory op = Build(
                    body
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            public async Task<AdminCreateExtensionCategory.Response> ExecuteAsync(
                RestapiExtensionCategoryApiRequest body
            )
            {
                AdminCreateExtensionCategory op = Build(
                    body
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        private AdminCreateExtensionCategory(AdminCreateExtensionCategoryBuilder builder,
            RestapiExtensionCategoryApiRequest body
        )
        {
            
            

            
            
            BodyParams = body;
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse<Model.RestapiExtensionCategoryApiResponse>
        {

            public RestapiErrorResponse? Error400 { get; set; } = null;

            public RestapiErrorResponse? Error500 { get; set; } = null;


            protected override string GetFullOperationId() => "Reporting::AdminExtensionCategoriesAndAutoModerationActions::AdminCreateExtensionCategory";
        }

        #endregion

        public AdminCreateExtensionCategory(
            Model.RestapiExtensionCategoryApiRequest body            
        )
        {
            
            

            
            
            BodyParams = body;
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/reporting/v1/admin/extensionCategories";

        public override HttpMethod Method => HttpMethod.Post;

        public override List<string> Consumes => new() { "application/json" };

        public override List<string> Produces => new() { "application/json" };
        
        public AdminCreateExtensionCategory.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new AdminCreateExtensionCategory.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Data = JsonSerializer.Deserialize<Model.RestapiExtensionCategoryApiResponse>(payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)400)
            {
                response.Error400 = JsonSerializer.Deserialize<RestapiErrorResponse>(payload, ResponseJsonOptions);
                response.Error = response.Error400!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)500)
            {
                response.Error500 = JsonSerializer.Deserialize<RestapiErrorResponse>(payload, ResponseJsonOptions);
                response.Error = response.Error500!.TranslateToApiError();
            }

            return response;
        }
    }

}