// Copyright (c) 2022-2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Platform.Model;

namespace AccelByte.Sdk.Api.Platform.Operation
{
    /// <summary>
    /// queryRewards
    ///
    /// This API is used to query rewards by criteria.
    /// 
    /// Other detail info:
    /// 
    ///   * Returns : the list of rewards
    /// </summary>
    public class QueryRewards : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static QueryRewardsBuilder Builder { get => new QueryRewardsBuilder(); }

        public interface IQueryRewardsBuilder
        {

            string? EventTopic { get; }

            int? Limit { get; }

            int? Offset { get; }

            List<QueryRewardsSortBy>? SortBy { get; }





        }

        public abstract class QueryRewardsAbstractBuilder<TImpl>
            : OperationBuilder<TImpl>, IQueryRewardsBuilder
            where TImpl : QueryRewardsAbstractBuilder<TImpl>
        {

            public string? EventTopic { get; set; }

            public int? Limit { get; set; }

            public int? Offset { get; set; }

            public List<QueryRewardsSortBy>? SortBy { get; set; }





            public QueryRewardsAbstractBuilder() { }

            public QueryRewardsAbstractBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }


            public TImpl SetEventTopic(string _eventTopic)
            {
                EventTopic = _eventTopic;
                return (TImpl)this;
            }

            public TImpl SetLimit(int _limit)
            {
                Limit = _limit;
                return (TImpl)this;
            }

            public TImpl SetOffset(int _offset)
            {
                Offset = _offset;
                return (TImpl)this;
            }

            public TImpl SetSortBy(List<QueryRewardsSortBy> _sortBy)
            {
                SortBy = _sortBy;
                return (TImpl)this;
            }





            public QueryRewards Build(
                string namespace_
            )
            {
                QueryRewards op = new QueryRewards(this,
                    namespace_                    
                );

                op.SetBaseFields<TImpl>(this);
                return op;
            }

            protected QueryRewards.Response InternalExecute(
                string namespace_
            )
            {
                QueryRewards op = Build(
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<QueryRewards.Response> InternalExecuteAsync(
                string namespace_
            )
            {
                QueryRewards op = Build(
                    namespace_
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        public class QueryRewardsBuilder : QueryRewardsAbstractBuilder<QueryRewardsBuilder>
        {
            public QueryRewardsBuilder() : base() { }

            public QueryRewardsBuilder(IAccelByteSdk sdk) : base(sdk) { }

            public QueryRewards.Response Execute(
                string namespace_
            )
            {
                return InternalExecute(
                    namespace_
                );
            }
            public async Task<QueryRewards.Response> ExecuteAsync(
                string namespace_
            )
            {
                return await InternalExecuteAsync(
                    namespace_
                );
            }
        }


        public QueryRewards(IQueryRewardsBuilder builder,
            string namespace_
        )
        {
            PathParams["namespace"] = namespace_;
            
            if (builder.EventTopic is not null) QueryParams["eventTopic"] = builder.EventTopic;
            if (builder.Limit != null) QueryParams["limit"] = Convert.ToString(builder.Limit)!;
            if (builder.Offset != null) QueryParams["offset"] = Convert.ToString(builder.Offset)!;
            if (builder.SortBy is not null) QueryParams["sortBy"] = builder.SortBy;
            

            
            CollectionFormatMap["sortBy"] = "csv";
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse<Model.RewardPagingSlicedResult>
        {

            public ValidationErrorEntity? Error422 { get; set; } = null;


            protected override string GetFullOperationId() => "Platform::Reward::QueryRewards";
        }

        #endregion

        public QueryRewards(
            string namespace_,            
            string? eventTopic,            
            int? limit,            
            int? offset,            
            List<QueryRewardsSortBy>? sortBy            
        )
        {
            PathParams["namespace"] = namespace_;
            
            if (eventTopic is not null) QueryParams["eventTopic"] = eventTopic;
            if (limit != null) QueryParams["limit"] = Convert.ToString(limit)!;
            if (offset != null) QueryParams["offset"] = Convert.ToString(offset)!;
            if (sortBy is not null) QueryParams["sortBy"] = sortBy;
            

            
            CollectionFormatMap["sortBy"] = "csv";
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/platform/admin/namespaces/{namespace}/rewards/byCriteria";

        public override HttpMethod Method => HttpMethod.Get;

        public override List<string> Consumes => new() {  };

        public override List<string> Produces => new() { "application/json" };
        
        public QueryRewards.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new QueryRewards.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Payload = payload.ReadToString();
                response.Data = JsonSerializer.Deserialize<Model.RewardPagingSlicedResult>(response.Payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)422)
            {
                response.Payload = payload.ReadToString();
                response.Error422 = JsonSerializer.Deserialize<ValidationErrorEntity>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error422!.TranslateToApiError();
            }

            return response;
        }
    }

    public class QueryRewardsSortBy : StringEnum<QueryRewardsSortBy>
    {
        public static readonly QueryRewardsSortBy Namespace
            = new QueryRewardsSortBy("namespace");

        public static readonly QueryRewardsSortBy Namespaceasc
            = new QueryRewardsSortBy("namespace:asc");

        public static readonly QueryRewardsSortBy Namespacedesc
            = new QueryRewardsSortBy("namespace:desc");

        public static readonly QueryRewardsSortBy RewardCode
            = new QueryRewardsSortBy("rewardCode");

        public static readonly QueryRewardsSortBy RewardCodeasc
            = new QueryRewardsSortBy("rewardCode:asc");

        public static readonly QueryRewardsSortBy RewardCodedesc
            = new QueryRewardsSortBy("rewardCode:desc");


        public static implicit operator QueryRewardsSortBy(string value)
        {
            return NewValue(value);
        }

        public QueryRewardsSortBy(string enumValue)
            : base(enumValue)
        {

        }
    }

}