// Copyright (c) 2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;

using AccelByte.Sdk.Api.Lobby.Model;
using AccelByte.Sdk.Api.Lobby.Operation;

namespace AccelByte.Sdk.Api.Lobby.Wrapper
{
    public class NotificationCompat
    {
        private readonly IAccelByteSdk _sdk;

        public NotificationCompat(IAccelByteSdk sdk)
        {
            _sdk = sdk;
        }

        #region Compat Operation Builders

        public class SendMultipleUsersFreeformNotificationV1AdminBuilderCompat : SendMultipleUsersFreeformNotificationV1Admin.SendMultipleUsersFreeformNotificationV1AdminAbstractBuilder<SendMultipleUsersFreeformNotificationV1AdminBuilderCompat>
        {
            internal SendMultipleUsersFreeformNotificationV1AdminBuilderCompat() : base() { }

            internal SendMultipleUsersFreeformNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelBulkUsersFreeFormNotificationRequestV1 body,
                string namespace_
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelBulkUsersFreeFormNotificationRequestV1 body,
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class SendUsersFreeformNotificationV1AdminBuilderCompat : SendUsersFreeformNotificationV1Admin.SendUsersFreeformNotificationV1AdminAbstractBuilder<SendUsersFreeformNotificationV1AdminBuilderCompat>
        {
            internal SendUsersFreeformNotificationV1AdminBuilderCompat() : base() { }

            internal SendUsersFreeformNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelFreeFormNotificationRequestV1 body,
                string namespace_
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelFreeFormNotificationRequestV1 body,
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public class SendPartyFreeformNotificationV1AdminBuilderCompat : SendPartyFreeformNotificationV1Admin.SendPartyFreeformNotificationV1AdminAbstractBuilder<SendPartyFreeformNotificationV1AdminBuilderCompat>
        {
            internal SendPartyFreeformNotificationV1AdminBuilderCompat() : base() { }

            internal SendPartyFreeformNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
            public void Execute(
                ModelFreeFormNotificationRequestV1 body,
                string namespace_,
                string partyId
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    partyId
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelFreeFormNotificationRequestV1 body,
                string namespace_,
                string partyId
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    partyId
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public class SendPartyTemplatedNotificationV1AdminBuilderCompat : SendPartyTemplatedNotificationV1Admin.SendPartyTemplatedNotificationV1AdminAbstractBuilder<SendPartyTemplatedNotificationV1AdminBuilderCompat>
        {
            internal SendPartyTemplatedNotificationV1AdminBuilderCompat() : base() { }

            internal SendPartyTemplatedNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
            public void Execute(
                ModelNotificationWithTemplateRequestV1 body,
                string namespace_,
                string partyId
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    partyId
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelNotificationWithTemplateRequestV1 body,
                string namespace_,
                string partyId
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    partyId
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetAllNotificationTemplatesV1AdminBuilderCompat : GetAllNotificationTemplatesV1Admin.GetAllNotificationTemplatesV1AdminAbstractBuilder<GetAllNotificationTemplatesV1AdminBuilderCompat>
        {
            internal GetAllNotificationTemplatesV1AdminBuilderCompat() : base() { }

            internal GetAllNotificationTemplatesV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public List<AccelByte.Sdk.Api.Lobby.Model.ModelNotificationTemplateResponse>? Execute(
                string namespace_
            )
            {
                var response = InternalExecute(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<List<AccelByte.Sdk.Api.Lobby.Model.ModelNotificationTemplateResponse>?> ExecuteAsync(
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class CreateNotificationTemplateV1AdminBuilderCompat : CreateNotificationTemplateV1Admin.CreateNotificationTemplateV1AdminAbstractBuilder<CreateNotificationTemplateV1AdminBuilderCompat>
        {
            internal CreateNotificationTemplateV1AdminBuilderCompat() : base() { }

            internal CreateNotificationTemplateV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelCreateTemplateRequest body,
                string namespace_
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelCreateTemplateRequest body,
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class SendUsersTemplatedNotificationV1AdminBuilderCompat : SendUsersTemplatedNotificationV1Admin.SendUsersTemplatedNotificationV1AdminAbstractBuilder<SendUsersTemplatedNotificationV1AdminBuilderCompat>
        {
            internal SendUsersTemplatedNotificationV1AdminBuilderCompat() : base() { }

            internal SendUsersTemplatedNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelNotificationWithTemplateRequestV1 body,
                string namespace_
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelNotificationWithTemplateRequestV1 body,
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetTemplateSlugLocalizationsTemplateV1AdminBuilderCompat : GetTemplateSlugLocalizationsTemplateV1Admin.GetTemplateSlugLocalizationsTemplateV1AdminAbstractBuilder<GetTemplateSlugLocalizationsTemplateV1AdminBuilderCompat>
        {
            internal GetTemplateSlugLocalizationsTemplateV1AdminBuilderCompat() : base() { }

            internal GetTemplateSlugLocalizationsTemplateV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelGetAllNotificationTemplateSlugResp? Execute(
                string namespace_,
                string templateSlug
            )
            {
                var response = InternalExecute(
                    namespace_,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelGetAllNotificationTemplateSlugResp?> ExecuteAsync(
                string namespace_,
                string templateSlug
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class DeleteNotificationTemplateSlugV1AdminBuilderCompat : DeleteNotificationTemplateSlugV1Admin.DeleteNotificationTemplateSlugV1AdminAbstractBuilder<DeleteNotificationTemplateSlugV1AdminBuilderCompat>
        {
            internal DeleteNotificationTemplateSlugV1AdminBuilderCompat() : base() { }

            internal DeleteNotificationTemplateSlugV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                string namespace_,
                string templateSlug
            )
            {
                var response = InternalExecute(
                    namespace_,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                string namespace_,
                string templateSlug
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetSingleTemplateLocalizationV1AdminBuilderCompat : GetSingleTemplateLocalizationV1Admin.GetSingleTemplateLocalizationV1AdminAbstractBuilder<GetSingleTemplateLocalizationV1AdminBuilderCompat>
        {
            internal GetSingleTemplateLocalizationV1AdminBuilderCompat() : base() { }

            internal GetSingleTemplateLocalizationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelLocalization? Execute(
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = InternalExecute(
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelLocalization?> ExecuteAsync(
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class UpdateTemplateLocalizationV1AdminBuilderCompat : UpdateTemplateLocalizationV1Admin.UpdateTemplateLocalizationV1AdminAbstractBuilder<UpdateTemplateLocalizationV1AdminBuilderCompat>
        {
            internal UpdateTemplateLocalizationV1AdminBuilderCompat() : base() { }

            internal UpdateTemplateLocalizationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelUpdateTemplateRequest body,
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelUpdateTemplateRequest body,
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class DeleteTemplateLocalizationV1AdminBuilderCompat : DeleteTemplateLocalizationV1Admin.DeleteTemplateLocalizationV1AdminAbstractBuilder<DeleteTemplateLocalizationV1AdminBuilderCompat>
        {
            internal DeleteTemplateLocalizationV1AdminBuilderCompat() : base() { }

            internal DeleteTemplateLocalizationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = InternalExecute(
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class PublishTemplateLocalizationV1AdminBuilderCompat : PublishTemplateLocalizationV1Admin.PublishTemplateLocalizationV1AdminAbstractBuilder<PublishTemplateLocalizationV1AdminBuilderCompat>
        {
            internal PublishTemplateLocalizationV1AdminBuilderCompat() : base() { }

            internal PublishTemplateLocalizationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = InternalExecute(
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                string namespace_,
                string templateLanguage,
                string templateSlug
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    templateLanguage,
                    templateSlug
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetAllNotificationTopicsV1AdminBuilderCompat : GetAllNotificationTopicsV1Admin.GetAllNotificationTopicsV1AdminAbstractBuilder<GetAllNotificationTopicsV1AdminBuilderCompat>
        {
            internal GetAllNotificationTopicsV1AdminBuilderCompat() : base() { }

            internal GetAllNotificationTopicsV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelGetAllNotificationTopicsResponse? Execute(
                string namespace_
            )
            {
                var response = InternalExecute(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelGetAllNotificationTopicsResponse?> ExecuteAsync(
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class CreateNotificationTopicV1AdminBuilderCompat : CreateNotificationTopicV1Admin.CreateNotificationTopicV1AdminAbstractBuilder<CreateNotificationTopicV1AdminBuilderCompat>
        {
            internal CreateNotificationTopicV1AdminBuilderCompat() : base() { }

            internal CreateNotificationTopicV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelCreateTopicRequestV1 body,
                string namespace_
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelCreateTopicRequestV1 body,
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetNotificationTopicV1AdminBuilderCompat : GetNotificationTopicV1Admin.GetNotificationTopicV1AdminAbstractBuilder<GetNotificationTopicV1AdminBuilderCompat>
        {
            internal GetNotificationTopicV1AdminBuilderCompat() : base() { }

            internal GetNotificationTopicV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelNotificationTopicResponseV1? Execute(
                string namespace_,
                string topicName
            )
            {
                var response = InternalExecute(
                    namespace_,
                    topicName
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelNotificationTopicResponseV1?> ExecuteAsync(
                string namespace_,
                string topicName
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    topicName
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class UpdateNotificationTopicV1AdminBuilderCompat : UpdateNotificationTopicV1Admin.UpdateNotificationTopicV1AdminAbstractBuilder<UpdateNotificationTopicV1AdminBuilderCompat>
        {
            internal UpdateNotificationTopicV1AdminBuilderCompat() : base() { }

            internal UpdateNotificationTopicV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelUpdateTopicRequest body,
                string namespace_,
                string topicName
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    topicName
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelUpdateTopicRequest body,
                string namespace_,
                string topicName
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    topicName
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class DeleteNotificationTopicV1AdminBuilderCompat : DeleteNotificationTopicV1Admin.DeleteNotificationTopicV1AdminAbstractBuilder<DeleteNotificationTopicV1AdminBuilderCompat>
        {
            internal DeleteNotificationTopicV1AdminBuilderCompat() : base() { }

            internal DeleteNotificationTopicV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                string namespace_,
                string topicName
            )
            {
                var response = InternalExecute(
                    namespace_,
                    topicName
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                string namespace_,
                string topicName
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    topicName
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class SendSpecificUserFreeformNotificationV1AdminBuilderCompat : SendSpecificUserFreeformNotificationV1Admin.SendSpecificUserFreeformNotificationV1AdminAbstractBuilder<SendSpecificUserFreeformNotificationV1AdminBuilderCompat>
        {
            internal SendSpecificUserFreeformNotificationV1AdminBuilderCompat() : base() { }

            internal SendSpecificUserFreeformNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelFreeFormNotificationRequestV1 body,
                string namespace_,
                string userId
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelFreeFormNotificationRequestV1 body,
                string namespace_,
                string userId
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class SendSpecificUserTemplatedNotificationV1AdminBuilderCompat : SendSpecificUserTemplatedNotificationV1Admin.SendSpecificUserTemplatedNotificationV1AdminAbstractBuilder<SendSpecificUserTemplatedNotificationV1AdminBuilderCompat>
        {
            internal SendSpecificUserTemplatedNotificationV1AdminBuilderCompat() : base() { }

            internal SendSpecificUserTemplatedNotificationV1AdminBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelNotificationWithTemplateRequestV1 body,
                string namespace_,
                string userId
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelNotificationWithTemplateRequestV1 body,
                string namespace_,
                string userId
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetMyNotificationsBuilderCompat : GetMyNotifications.GetMyNotificationsAbstractBuilder<GetMyNotificationsBuilderCompat>
        {
            internal GetMyNotificationsBuilderCompat() : base() { }

            internal GetMyNotificationsBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelNotificationResponse? Execute(
                string namespace_
            )
            {
                var response = InternalExecute(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelNotificationResponse?> ExecuteAsync(
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class GetMyOfflineNotificationsBuilderCompat : GetMyOfflineNotifications.GetMyOfflineNotificationsAbstractBuilder<GetMyOfflineNotificationsBuilderCompat>
        {
            internal GetMyOfflineNotificationsBuilderCompat() : base() { }

            internal GetMyOfflineNotificationsBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelNotificationsResponse? Execute(
                string namespace_
            )
            {
                var response = InternalExecute(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelNotificationsResponse?> ExecuteAsync(
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class GetTopicByNamespaceBuilderCompat : GetTopicByNamespace.GetTopicByNamespaceAbstractBuilder<GetTopicByNamespaceBuilderCompat>
        {
            internal GetTopicByNamespaceBuilderCompat() : base() { }

            internal GetTopicByNamespaceBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelTopicByNamespacesResponse? Execute(
                string namespace_
            )
            {
                var response = InternalExecute(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelTopicByNamespacesResponse?> ExecuteAsync(
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class CreateTopicBuilderCompat : CreateTopic.CreateTopicAbstractBuilder<CreateTopicBuilderCompat>
        {
            internal CreateTopicBuilderCompat() : base() { }

            internal CreateTopicBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelCreateTopicRequest body,
                string namespace_
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelCreateTopicRequest body,
                string namespace_
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class GetTopicByTopicNameBuilderCompat : GetTopicByTopicName.GetTopicByTopicNameAbstractBuilder<GetTopicByTopicNameBuilderCompat>
        {
            internal GetTopicByTopicNameBuilderCompat() : base() { }

            internal GetTopicByTopicNameBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public AccelByte.Sdk.Api.Lobby.Model.ModelNotificationTopicResponse? Execute(
                string namespace_,
                string topic
            )
            {
                var response = InternalExecute(
                    namespace_,
                    topic
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
            public async Task<AccelByte.Sdk.Api.Lobby.Model.ModelNotificationTopicResponse?> ExecuteAsync(
                string namespace_,
                string topic
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    topic
                );
                response.ThrowHttpExceptionIfError();
                return response.Data;
            }
        }

        public class UpdateTopicByTopicNameBuilderCompat : UpdateTopicByTopicName.UpdateTopicByTopicNameAbstractBuilder<UpdateTopicByTopicNameBuilderCompat>
        {
            internal UpdateTopicByTopicNameBuilderCompat() : base() { }

            internal UpdateTopicByTopicNameBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelUpdateTopicRequest body,
                string namespace_,
                string topic
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    topic
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelUpdateTopicRequest body,
                string namespace_,
                string topic
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    topic
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class DeleteTopicByTopicNameBuilderCompat : DeleteTopicByTopicName.DeleteTopicByTopicNameAbstractBuilder<DeleteTopicByTopicNameBuilderCompat>
        {
            internal DeleteTopicByTopicNameBuilderCompat() : base() { }

            internal DeleteTopicByTopicNameBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                string namespace_,
                string topic
            )
            {
                var response = InternalExecute(
                    namespace_,
                    topic
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                string namespace_,
                string topic
            )
            {
                var response = await InternalExecuteAsync(
                    namespace_,
                    topic
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class FreeFormNotificationByUserIDBuilderCompat : FreeFormNotificationByUserID.FreeFormNotificationByUserIDAbstractBuilder<FreeFormNotificationByUserIDBuilderCompat>
        {
            internal FreeFormNotificationByUserIDBuilderCompat() : base() { }

            internal FreeFormNotificationByUserIDBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelFreeFormNotificationRequest body,
                string namespace_,
                string userId
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelFreeFormNotificationRequest body,
                string namespace_,
                string userId
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
        }

        public class NotificationWithTemplateByUserIDBuilderCompat : NotificationWithTemplateByUserID.NotificationWithTemplateByUserIDAbstractBuilder<NotificationWithTemplateByUserIDBuilderCompat>
        {
            internal NotificationWithTemplateByUserIDBuilderCompat() : base() { }

            internal NotificationWithTemplateByUserIDBuilderCompat(IAccelByteSdk sdk) : base(sdk) { }

            public void Execute(
                ModelNotificationWithTemplateRequest body,
                string namespace_,
                string userId
            )
            {
                var response = InternalExecute(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
            public async Task ExecuteAsync(
                ModelNotificationWithTemplateRequest body,
                string namespace_,
                string userId
            )
            {
                var response = await InternalExecuteAsync(
                    body,
                    namespace_,
                    userId
                );
                response.ThrowHttpExceptionIfError();
            }
        }
        #endregion

        #region Operation Builders
        public SendMultipleUsersFreeformNotificationV1AdminBuilderCompat SendMultipleUsersFreeformNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendMultipleUsersFreeformNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public SendUsersFreeformNotificationV1AdminBuilderCompat SendUsersFreeformNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendUsersFreeformNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public SendPartyFreeformNotificationV1AdminBuilderCompat SendPartyFreeformNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendPartyFreeformNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public SendPartyTemplatedNotificationV1AdminBuilderCompat SendPartyTemplatedNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendPartyTemplatedNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetAllNotificationTemplatesV1AdminBuilderCompat GetAllNotificationTemplatesV1AdminOp
        {
            get
            {
                var opBuilder = new GetAllNotificationTemplatesV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public CreateNotificationTemplateV1AdminBuilderCompat CreateNotificationTemplateV1AdminOp
        {
            get
            {
                var opBuilder = new CreateNotificationTemplateV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public SendUsersTemplatedNotificationV1AdminBuilderCompat SendUsersTemplatedNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendUsersTemplatedNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetTemplateSlugLocalizationsTemplateV1AdminBuilderCompat GetTemplateSlugLocalizationsTemplateV1AdminOp
        {
            get
            {
                var opBuilder = new GetTemplateSlugLocalizationsTemplateV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public DeleteNotificationTemplateSlugV1AdminBuilderCompat DeleteNotificationTemplateSlugV1AdminOp
        {
            get
            {
                var opBuilder = new DeleteNotificationTemplateSlugV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetSingleTemplateLocalizationV1AdminBuilderCompat GetSingleTemplateLocalizationV1AdminOp
        {
            get
            {
                var opBuilder = new GetSingleTemplateLocalizationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public UpdateTemplateLocalizationV1AdminBuilderCompat UpdateTemplateLocalizationV1AdminOp
        {
            get
            {
                var opBuilder = new UpdateTemplateLocalizationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public DeleteTemplateLocalizationV1AdminBuilderCompat DeleteTemplateLocalizationV1AdminOp
        {
            get
            {
                var opBuilder = new DeleteTemplateLocalizationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public PublishTemplateLocalizationV1AdminBuilderCompat PublishTemplateLocalizationV1AdminOp
        {
            get
            {
                var opBuilder = new PublishTemplateLocalizationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetAllNotificationTopicsV1AdminBuilderCompat GetAllNotificationTopicsV1AdminOp
        {
            get
            {
                var opBuilder = new GetAllNotificationTopicsV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public CreateNotificationTopicV1AdminBuilderCompat CreateNotificationTopicV1AdminOp
        {
            get
            {
                var opBuilder = new CreateNotificationTopicV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetNotificationTopicV1AdminBuilderCompat GetNotificationTopicV1AdminOp
        {
            get
            {
                var opBuilder = new GetNotificationTopicV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public UpdateNotificationTopicV1AdminBuilderCompat UpdateNotificationTopicV1AdminOp
        {
            get
            {
                var opBuilder = new UpdateNotificationTopicV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public DeleteNotificationTopicV1AdminBuilderCompat DeleteNotificationTopicV1AdminOp
        {
            get
            {
                var opBuilder = new DeleteNotificationTopicV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public SendSpecificUserFreeformNotificationV1AdminBuilderCompat SendSpecificUserFreeformNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendSpecificUserFreeformNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public SendSpecificUserTemplatedNotificationV1AdminBuilderCompat SendSpecificUserTemplatedNotificationV1AdminOp
        {
            get
            {
                var opBuilder = new SendSpecificUserTemplatedNotificationV1AdminBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetMyNotificationsBuilderCompat GetMyNotificationsOp
        {
            get
            {
                var opBuilder = new GetMyNotificationsBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetMyOfflineNotificationsBuilderCompat GetMyOfflineNotificationsOp
        {
            get
            {
                var opBuilder = new GetMyOfflineNotificationsBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetTopicByNamespaceBuilderCompat GetTopicByNamespaceOp
        {
            get
            {
                var opBuilder = new GetTopicByNamespaceBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public CreateTopicBuilderCompat CreateTopicOp
        {
            get
            {
                var opBuilder = new CreateTopicBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public GetTopicByTopicNameBuilderCompat GetTopicByTopicNameOp
        {
            get
            {
                var opBuilder = new GetTopicByTopicNameBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public UpdateTopicByTopicNameBuilderCompat UpdateTopicByTopicNameOp
        {
            get
            {
                var opBuilder = new UpdateTopicByTopicNameBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public DeleteTopicByTopicNameBuilderCompat DeleteTopicByTopicNameOp
        {
            get
            {
                var opBuilder = new DeleteTopicByTopicNameBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public FreeFormNotificationByUserIDBuilderCompat FreeFormNotificationByUserIDOp
        {
            get
            {
                var opBuilder = new FreeFormNotificationByUserIDBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        public NotificationWithTemplateByUserIDBuilderCompat NotificationWithTemplateByUserIDOp
        {
            get
            {
                var opBuilder = new NotificationWithTemplateByUserIDBuilderCompat(_sdk);
                return opBuilder;
            }
        }
        #endregion
    }
}