// Copyright (c) 2022-2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Legal.Model;

namespace AccelByte.Sdk.Api.Legal.Operation
{
    /// <summary>
    /// retrieveAllPolicyTypes
    ///
    /// Retrieve all supported policy types.
    /// </summary>
    public class RetrieveAllPolicyTypes : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static RetrieveAllPolicyTypesBuilder Builder { get => new RetrieveAllPolicyTypesBuilder(); }

        public class RetrieveAllPolicyTypesBuilder
            : OperationBuilder<RetrieveAllPolicyTypesBuilder>
        {

            public int? Offset { get; set; }





            internal RetrieveAllPolicyTypesBuilder() { }

            internal RetrieveAllPolicyTypesBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }


            public RetrieveAllPolicyTypesBuilder SetOffset(int _offset)
            {
                Offset = _offset;
                return this;
            }





            public RetrieveAllPolicyTypes Build(
                string namespace_,
                int limit
            )
            {
                RetrieveAllPolicyTypes op = new RetrieveAllPolicyTypes(this,
                    namespace_,                    
                    limit                    
                );

                op.SetBaseFields<RetrieveAllPolicyTypesBuilder>(this);
                return op;
            }

            public RetrieveAllPolicyTypes.Response Execute(
                string namespace_,
                int limit
            )
            {
                RetrieveAllPolicyTypes op = Build(
                    namespace_,
                    limit
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            public async Task<RetrieveAllPolicyTypes.Response> ExecuteAsync(
                string namespace_,
                int limit
            )
            {
                RetrieveAllPolicyTypes op = Build(
                    namespace_,
                    limit
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        private RetrieveAllPolicyTypes(RetrieveAllPolicyTypesBuilder builder,
            string namespace_,
            int limit
        )
        {
            PathParams["namespace"] = namespace_;
            
            if (builder.Offset != null) QueryParams["offset"] = Convert.ToString(builder.Offset)!;
            
            QueryParams["limit"] = Convert.ToString(limit)!;
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse<List<Model.RetrievePolicyTypeResponse>>
        {


            protected override string GetFullOperationId() => "Legal::BaseLegalPoliciesWithNamespace::RetrieveAllPolicyTypes";
        }

        #endregion

        public RetrieveAllPolicyTypes(
            string namespace_,            
            int? offset,            
            int limit            
        )
        {
            PathParams["namespace"] = namespace_;
            
            if (offset != null) QueryParams["offset"] = Convert.ToString(offset)!;
            
            QueryParams["limit"] = Convert.ToString(limit)!;
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/agreement/admin/namespaces/{namespace}/policy-types";

        public override HttpMethod Method => HttpMethod.Get;

        public override List<string> Consumes => new() {  };

        public override List<string> Produces => new() { "application/json" };
        
        public RetrieveAllPolicyTypes.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new RetrieveAllPolicyTypes.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Data = JsonSerializer.Deserialize<List<Model.RetrievePolicyTypeResponse>>(payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }

            return response;
        }
    }

}