// Copyright (c) 2022-2026 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http;
using System.IO;
using System.Threading.Tasks;

using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Net.Http;

using AccelByte.Sdk.Api.Iam.Model;

namespace AccelByte.Sdk.Api.Iam.Operation
{
    /// <summary>
    /// AdminGetUserDeviceBansV4
    ///
    /// This is the endpoint for an admin to get device bans of user
    /// </summary>
    public class AdminGetUserDeviceBansV4 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AdminGetUserDeviceBansV4Builder Builder { get => new AdminGetUserDeviceBansV4Builder(); }

        public interface IAdminGetUserDeviceBansV4Builder
        {





        }

        public abstract class AdminGetUserDeviceBansV4AbstractBuilder<TImpl>
            : OperationBuilder<TImpl>, IAdminGetUserDeviceBansV4Builder
            where TImpl : AdminGetUserDeviceBansV4AbstractBuilder<TImpl>
        {





            public AdminGetUserDeviceBansV4AbstractBuilder() { }

            public AdminGetUserDeviceBansV4AbstractBuilder(IAccelByteSdk sdk)
            {
                _Sdk = sdk;
            }






            public AdminGetUserDeviceBansV4 Build(
                string namespace_,
                string userId
            )
            {
                AdminGetUserDeviceBansV4 op = new AdminGetUserDeviceBansV4(this,
                    namespace_,                    
                    userId                    
                );

                op.SetBaseFields<TImpl>(this);
                return op;
            }

            protected AdminGetUserDeviceBansV4.Response InternalExecute(
                string namespace_,
                string userId
            )
            {
                AdminGetUserDeviceBansV4 op = Build(
                    namespace_,
                    userId
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = _Sdk.RunRequest(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
            protected async Task<AdminGetUserDeviceBansV4.Response> InternalExecuteAsync(
                string namespace_,
                string userId
            )
            {
                AdminGetUserDeviceBansV4 op = Build(
                    namespace_,
                    userId
                );

                if (_Sdk == null)
                    throw IncompleteComponentException.NoSdkObject;

                var response = await _Sdk.RunRequestAsync(op);
                return op.ParseResponse(
                    response.Code, 
                    response.ContentType,
                    response.Payload);
            }
        }

        public class AdminGetUserDeviceBansV4Builder : AdminGetUserDeviceBansV4AbstractBuilder<AdminGetUserDeviceBansV4Builder>
        {
            public AdminGetUserDeviceBansV4Builder() : base() { }

            public AdminGetUserDeviceBansV4Builder(IAccelByteSdk sdk) : base(sdk) { }

            public AdminGetUserDeviceBansV4.Response Execute(
                string namespace_,
                string userId
            )
            {
                return InternalExecute(
                    namespace_,
                    userId
                );
            }
            public async Task<AdminGetUserDeviceBansV4.Response> ExecuteAsync(
                string namespace_,
                string userId
            )
            {
                return await InternalExecuteAsync(
                    namespace_,
                    userId
                );
            }
        }


        public AdminGetUserDeviceBansV4(IAdminGetUserDeviceBansV4Builder builder,
            string namespace_,
            string userId
        )
        {
            PathParams["namespace"] = namespace_;
            
            if (userId is not null) QueryParams["userId"] = userId;
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        #region Response Part        
        public class Response : ApiResponse<Model.ModelDeviceBansResponseV4>
        {

            public RestErrorResponse? Error401 { get; set; } = null;

            public RestErrorResponse? Error403 { get; set; } = null;

            public RestErrorResponse? Error404 { get; set; } = null;

            public RestErrorResponse? Error500 { get; set; } = null;


            protected override string GetFullOperationId() => "Iam::DevicesV4::AdminGetUserDeviceBansV4";
        }

        #endregion

        public AdminGetUserDeviceBansV4(
            string namespace_,            
            string userId            
        )
        {
            PathParams["namespace"] = namespace_;
            
            if (userId is not null) QueryParams["userId"] = userId;
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/iam/v4/admin/namespaces/{namespace}/devices/bans";

        public override HttpMethod Method => HttpMethod.Get;

        public override List<string> Consumes => new() { "application/json" };

        public override List<string> Produces => new() { "application/json" };
        
        public AdminGetUserDeviceBansV4.Response ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            var response = new AdminGetUserDeviceBansV4.Response()
            {
                StatusCode = code,
                ContentType = contentType
            };

            if (code == (HttpStatusCode)204)
            {
                response.IsSuccess = true;
            }
            else if ((code == (HttpStatusCode)201) || (code == (HttpStatusCode)202) || (code == (HttpStatusCode)200))
            {
                response.Payload = payload.ReadToString();
                response.Data = JsonSerializer.Deserialize<Model.ModelDeviceBansResponseV4>(response.Payload, ResponseJsonOptions);
                response.IsSuccess = true;
            }
            else if (code == (HttpStatusCode)401)
            {
                response.Payload = payload.ReadToString();
                response.Error401 = JsonSerializer.Deserialize<RestErrorResponse>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error401!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)403)
            {
                response.Payload = payload.ReadToString();
                response.Error403 = JsonSerializer.Deserialize<RestErrorResponse>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error403!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)404)
            {
                response.Payload = payload.ReadToString();
                response.Error404 = JsonSerializer.Deserialize<RestErrorResponse>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error404!.TranslateToApiError();
            }
            else if (code == (HttpStatusCode)500)
            {
                response.Payload = payload.ReadToString();
                response.Error500 = JsonSerializer.Deserialize<RestErrorResponse>(response.Payload, ResponseJsonOptions);
                response.Error = response.Error500!.TranslateToApiError();
            }

            return response;
        }
    }

}